// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkOFbtDmNf7j3FD117fcaitoLMCzKQfLc',
    appId: '1:1041806987147:web:ad7231b1fa0c33a9afa98e',
    messagingSenderId: '1041806987147',
    projectId: 'travely1',
    authDomain: 'travely1.firebaseapp.com',
    storageBucket: 'travely1.firebasestorage.app',
    measurementId: 'G-L5Q2MMKN4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54wJB2XFm1PtLf-uXV_li4A8JZw_N5ks',
    appId: '1:1041806987147:android:c6519e209e206234afa98e',
    messagingSenderId: '1041806987147',
    projectId: 'travely1',
    storageBucket: 'travely1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHqPgHi-J3euSHT_NkfvK9E_O6tfOeuIo',
    appId: '1:1041806987147:ios:6a172f9bf741d1ccafa98e',
    messagingSenderId: '1041806987147',
    projectId: 'travely1',
    storageBucket: 'travely1.firebasestorage.app',
    iosBundleId: 'com.example.travely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHqPgHi-J3euSHT_NkfvK9E_O6tfOeuIo',
    appId: '1:1041806987147:ios:6a172f9bf741d1ccafa98e',
    messagingSenderId: '1041806987147',
    projectId: 'travely1',
    storageBucket: 'travely1.firebasestorage.app',
    iosBundleId: 'com.example.travely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkOFbtDmNf7j3FD117fcaitoLMCzKQfLc',
    appId: '1:1041806987147:web:38800bea93d2ffc4afa98e',
    messagingSenderId: '1041806987147',
    projectId: 'travely1',
    authDomain: 'travely1.firebaseapp.com',
    storageBucket: 'travely1.firebasestorage.app',
    measurementId: 'G-DP7Z5Q4R38',
  );
}
